routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::resource('todo', 'TodosController');//susikuria visi route
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//susikuriam Route naujai funkcijai aprasytai controller
Route::post('/todo/change-status/{id}/{status}', 'todosController@changeStatus')->name('todo.changestatus');

app/Todo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    protected $table = 'todo';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TodosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;  
use Session; 
use App\Todo;
use App;
use Gate;

class TodosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $todo = Todo::all();
        return view( 'todo.index',["todo" =>$todo] );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view( 'todo.create' );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    /**
    id - todo list item id
    status - status of item
        -- 0 = undone
        -- 1 = done
        -- 2 = waiting for review 
        susikuriame funkcija nauja kuri mums keis busena
    */
    public function changeStatus($id, $busena) {
        $todo = Todo::find($id);

        $todo->busena = $busena;

        $todo->save();

        return redirect()->route('todo.index');
    }

    public function store(Request $request)
    {
        $todo                       = new Todo;
        $todo->todo  = $request->todo;
        $todo->busena = $request->busena;
        $todo->save();
       Session::flash( 'status', 'Uzduotis pateikta' );


       return redirect()->route( 'todo.index' );//
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $todo = Todo::find($id);
        $todo->delete();
        Session::flash( 'status', 'Info ištrinta sėkmingai !' );
        return redirect()->route('todo.index');//istrinam ir einam i puslapi su visais automobiliais
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet"> <!-- nuoroda i naujai sukurta stiliu -->
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/createForm.blade.php
<form action="{{ route('todo.store') }}" method="POST">

	{{ csrf_field() }}
	<div class="row">
	<div class="col-md-8">
	<div class="form-group">
		<input type="text" class="form-control" placeholder="Iveskite uzduoties pavadinima" name="title">
	</div>
	</div>
	<div class="col-md-4">
		<input type="submit"  value="Ivesti" class="btn btn-info">
	</div>
</div>

</form>

resources/views/todo/index.blade.php
@extends("layouts.app")

@section('content')


 <div class="container">
          {{-- klaidu isvedimas pagal Laravel validatoriu --}}
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('todo.store') }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            
            <input
                    class="form-control"
                    placeholder="uzduotis"
                    value="{{ old('uzduotis') }}"
                    type="text" 
                    name="todo">

            <input
                    class="form-control" 
                    placeholder="busena"
                    value="{{ old('busena') }}"
                    type="text" 
                    name="busena">
            
            
            <input class="btn btn-success" type="submit" value="ivesti">
        </form>
        
    </div>
    <table class="table">
           <h3>Uzduociu sarasas</h3>
           <thead>
                <tr>
                    <th>Uzduotis </th>
                    <th>Busena</th>
                    <th>Veiksmas</th>
                    <th>Veiksmas</th>
                                     
                </tr>
            </thead>
            @foreach ($todo as $todo)
                <tr>
                    <td>{{ $todo->todo }} </td>
                    <td>{{ $todo->busena }} </td>
                    <td>
                        @if($todo->busena == 1)
					<button class="btn info">Uzduotis atlikta</button>
					<form action="{{ route('todo.changestatus', [$todo->id, 0])}}" method="POST">
						{{ csrf_field() }}
						<input type="submit" value="Padaryti kaip nebaigta" class="btn btn-success">
					</form>
				@else
					<form action="{{ route('todo.changestatus', [$todo->id, 1])}}" method="POST">
						{{ csrf_field() }}
						<input type="submit" value="Baigti" class="btn btn-success">
					</form>
				@endif
                    </td>
                     <td>
                        <form action="{{ route('todo.destroy', $todo
                        ->id) }}" method="POST">
                            <!--  Su post metodu dirbant sau formom visada butina ideti sita laukeli  -->
                        {{ csrf_field() }}
                        {{ method_field('delete')}}
                            <input 
                            class="btn btn-danger"
                            type="submit" value="Ištrinti">
                        </form>
                    </td>


                </tr>
            @endforeach
    </table>                
@endsection